api_endpoint: "https://ai-service-3883fcac-5a9a-4157-a321-00af3a6d6cc5-322dbepmma-an.a.run.app/chat"
api_key: "4d6206ba-2908-4a"
stg_api_endpoint: "https://ai-service-3883fcac-5a9a-4157-a321-00af3a6d6cc5-322dbepmma-an.a.run.app/chat"
stg_api_key: "4d6206ba-2908-4a"
log:
  directory: "logs"
  system_file: "system.log"
  request_file: "chat-requests.log"
